algoritmo "soma infinita"
// Função :soma os valores e dá uma resposta na hora
// Autor :Victor Hugo Faria & Paulo Henrique Frade
// Data : 05/04/2017
// Seção de Declarações 
var
y,z: real//declara as variáveis
inicio
// Seção de Comandos 
Escreval("Escreva números para soma e quando quiser finalizar digite 0")
repita
leia(z)//Lê para a variável z
y<-y+z//soma o valor anterior a z

Escreval(y)//escreve y
ate(z=0)//finaliza a repetição quando z=0
fimalgoritmo

